<div class="container">
    <div class="innercontent row margin-top-40">
    <div class="col-md-12 form-container" style="padding:10px 60px; border:#e3e2e2 1px solid;">
<h3 class="text-center margin-top-30">Terms of Use</h3>
<div class="row margin-bottom-40">
<div class="col-md-1"></div>
<div class="col-md-10">
	
  <p>This web page represents a legal document that serves as our Terms  of Use and it governs the legal terms of our website, http://www.cmpForYou.com,  sub-domains, and any associated web-based and mobile applications  (collectively, &quot;Website&quot;), as owned and operated by Custom Med  Patient Services Inc..<br />
  Capitalized terms, unless otherwise defined, have the meaning  specified within the Definitions section below. This Terms of Use, along with  our Privacy Policy, any mobile license agreement, and other posted guidelines  within our Website, collectively &quot;Legal Terms&quot;, constitute the entire  and only agreement between you and Custom Med Patient Services Inc., and  supersede all other agreements, representations, warranties and understandings  with respect to our Website and the subject matter contained herein. We may  amend our Legal Terms at any time without specific notice to you. The latest  copies of our Legal Terms will be posted on our Website, and you should review  all Legal Terms prior to using our Website. After any revisions to our Legal  Terms are posted, you agree to be bound to any such changes to them. Therefore,  it is important for you to periodically review our Legal Terms to make sure you  still agree to them.<br />
  By accessing this web site, you are agreeing to be bound by these  Website Terms and Conditions of Use, all applicable laws and regulations, and  agree that you are responsible for compliance with any applicable local laws.  If you do not agree with any of these terms, you are prohibited from using or  accessing this site. The materials contained in this Website are protected by  applicable copyright and trademark law.<br />
  The last update to our Terms of Use was posted on 24 May 2015.</p>
<p><strong>Definitions</strong><br />
  The terms &quot;us&quot; or &quot;we&quot; or &quot;our&quot; refers to Custom  Med Patient Services Inc., the owner of the Website.<br />
  A &quot;Visitor&quot; is someone who merely browses our Website,  but has not registered as Member.<br />
  A &quot;Member&quot; is an individual that has registered with us  to use our Service.<br />
  Our &quot;Service&quot; represents the collective functionality  and features as offered through our Website to our Members.<br />
  A &quot;User&quot; is a collective identifier that refers to  either a Visitor or a Member.<br />
  All text, information, graphics, audio, video, and data offered  through our Website are collectively known as our &quot;Content&quot;.</p>
<p><strong>Use License</strong> </p>
<ol class="list-items">
  <li>Permission is granted to temporarily download one copy of the  materials (information or software) on Custom Med Patient Services Inc.&rsquo;s  Website for personal, non-commercial transitory viewing only. This is the grant  of a license, not a transfer of title, and under this license you may not:</li>
  <ol>
    <li>modify or copy the materials;</li>
    <li>use the materials for any commercial purpose, or for any public  display (commercial or non-commercial);</li>
    <li>attempt to decompile or reverse engineer any software contained on  Custom Med Patient Services Inc.&rsquo;s web site;</li>
    <li>remove any copyright or other proprietary notations from the  materials; or</li>
    <li>transfer the materials to another person or &ldquo;mirror&rdquo; the materials  on any other server.</li>
  </ol>
  <li>This license shall automatically terminate if you violate any of  these restrictions and may be terminated by Custom Med Patient Services Inc. at  any time. Upon terminating your viewing of these materials or upon the  termination of this license, you must destroy any downloaded materials in your  possession whether in electronic or printed format.</li>
</ol>
<p><strong>Restricted Uses<br />
  </strong><br />
  Listing of offered products on the Website could be used only for lawful  purposes by Users of the Website. You could not frame or utilize framing  techniques to enclose any hallmark, logo, copyrighted image, or most  proprietary details (consisting of images, text, page layout, or type) of  Custom Med Patient Services Inc. without express composed consent. You might  not use any meta tags or any various other &quot;unseen text&quot; utilizing  Custom Med Patient Services Inc.'s name or trademarks without the express  written consent of Custom Med Patient Services Inc.. You agree not to offer or  modify any content found on the Website consisting of, however not limited to,  names of Users and Content, or to recreate, display, openly perform,  distribute, or otherwise make use of the Material, in any way for any public  function, in connection with services or products that are not those of Custom  Med Patient Services Inc., in other way that is likely to trigger confusion  among consumers, that disparages or challenges Custom Med Patient Services Inc.  or its licensors, that dilutes the strength of Custom Med Patient Services  Inc.'s or its licensor's residential property, or that otherwise infringes  Custom Med Patient Services Inc.'s or its licensor's copyright rights. You also  agree to abstain from abusing any of the material that appears on the Site. The  use of the Material on any other website or in a networked computer system  environment for any purpose is prohibited. Any code that Custom Med Patient  Services Inc. develops to generate or show any Material of the pages making up  the Website is likewise secured by Custom Med Patient Services Inc.'s  copyright, and you may not copy or adjust such code.<br />
  Custom Med Patient Services Inc. has no duty to keep track of any  products published, transferred, or connected to or with the Site. If you think  that something on the Website breaches these Terms please contact our marked  representative as set forth below.</p>
<p>  If alerted by a User of any  products which allegedly do not conform to these Terms, Custom Med Patient  Services Inc. could in its single discernment explore the allegation and figure  out whether to take other actions or ask for the removal or get rid of the  Content. Custom Med Patient Services Inc. has no liability or duty to  Individuals for efficiency or nonperformance of such activities.<br />
  Our company is not a Medical Consultancy Firm and does not deal in providing  health assistance. The content which is written on our site is not for medical  practice. The readers and visitors should seek proper treatment by taking help  from your own&nbsp; doctor or an&nbsp; health care provider. In case of&nbsp; health emergency , call&nbsp; 911 immediately. </p>
<p>Online consultancy by  messaging or&nbsp; video&nbsp; is there for you to get proper information  regarding your health. </p>
<p>&nbsp;We&nbsp; do  not provide a 24 hour services for emergency situations nor&nbsp; we will take any request in critical  conditions.&nbsp;&nbsp;&nbsp; <br />
  In case, if you need help  regarding mental health services then approach National Mental Health  Association Information Center. There are few things that need to be clear  regarding the National Mental Association Information Center (nmha.org). We are  there to provide informational &amp; educational based resources to you and we  are not engaged in any clinical or licensed medical or psychological field&nbsp; practice.</p>
<p><strong>Electronic Communication<br />
  </strong><br />
  You are connecting with us electronically when you go to the Website or send  out emails to us. You consent to get interactions from us online. We will  connect with you by email or by uploading notifications on the Site. You concur  that all contracts notifications, disclosure, and various other communicates  that we provide to you digitally satisfy any legal requirements that such  communications be in writing.<br />
  <strong>Your Account<br />
  </strong><br />
  If you utilize the Website, you are accountable for maintaining the  confidentiality of your account and password and you accept responsibility for  all activities that happen under your account and password. You also accept not  to reveal any personally identifiable information, consisting of, however not  limited to, first and last names, credentials, or various other details of a  personal nature (&quot;Personal Data&quot;) from the Site. Your disclosure of  any Personal Data on the website might result in the immediate termination of  your account. Custom Med Patient Services Inc. additionally reserves the right  to refuse service, terminate accounts, and remove or edit Content at it's sole  discernment.<br />
  Custom Med Patient Services Inc. does not guarantee the  truthfulness or represent, precision, or dependability of Content on the site,  consisting of Personal Data. Each Individual is accountable for upgrading and  changing any pertinent account info when essential to preserve the truthfulness,  precision, or reliability of the details.<br />
  <strong>Reviews, Comments, and Other Material<br />
  </strong><br />
  Registered Users of the Website might post evaluations and remarks of a product  and services purchased by means of the Website, so long as the Material is not  unlawful, profane, threatening, defamatory, an invasive of privacy, infringing  of intellectual property rights, or otherwise injurious to third parties or  objectionable and does not include or include industrial solicitation, mass  mailings, or any type of &quot;spam.&quot; You may not use another User's  account to impersonate a User or entity, or otherwise deceived as to the origin  of the opinions. Custom Med Patient Services Inc. books the right (however is  not bound) to eliminate or modify such Material, but does not regularly examine  posted Material.</p>
<p>  If you post an evaluation  or send comments, and unless Custom Med Patient Services Inc. suggests  otherwise, you grant Custom Med Patient Services Inc. a nonexclusive,  royalty-free, permanent, irrevocable, and completely sublicensable right to  utilize, recreate, modify, adjust, release, equate, create derivative works  from, distribute, and screen such content throughout the world, in any media.  You grant Custom Med Patient Services Inc. and sublicenses the right to utilize  your name in connection with such Material, if they choose. You represent and  require that You own or otherwise control all the rights to the content that  You post; that the content is accurate; that use of the content You supply does  not violate this policy and will not trigger injury to anyone or entity; which  You will indemnify Custom Med Patient Services Inc. for all claims resulting  from Content You supply. Custom Med Patient Services Inc. has the right but not  the commitment to edit and keep track of or eliminate any task or Material.  Custom Med Patient Services Inc. takes no duty and assumes no liability for any  content published by You or any 3rd party.<br />
  <br />
  <strong>No promise of Certification</strong> <br />
  <br />
  Even though we have consultants listed on our website,&nbsp; we are more focused to keep their&nbsp; records and not responsible for the  authentication. There is no&nbsp; assurance  for any of the consultants background, qualification &amp; knowledge even if  they are&nbsp; engaged in the clinical  practices. There are no recommendations made on the list of the  consultants,&nbsp; either of endorsement or  guarantee on the abilities or qualification of any of the consultant or about  the services. <br />
  <br />
  In case if any consultant  is negligent, we will not be responsible for such negligence. The information,  suggestion and opinions belong to the consultants and are not endorsed by us.  So we will not liable, if any negligence occurred from the consultants end  because we do not pass decisions regarding the consultation.<br />
  There is no assurance that  if a&nbsp; person, who uses the website for  getting&nbsp; medical advice will get the  right&nbsp; advice . We are not responsible  for any advice given by anybody on our website.<br />
  The information which will  be shared on or through the website interaction will stay confidential and it  will not lead to any client-professional relationships.<br />
  It will be your  responsibility&nbsp; to check the  certification and proper licensing of the person you are involving in your  healthcare. <br />
  <br />
  Making the information  available to you&nbsp;&nbsp; is what we can do. If you  undertake any implementation of courses recommended by the health provider,  then you will be responsible for the risk that could be involved in it. On the  other hand we will try our level best in verifying consultant's background to  make&nbsp; sure they are authentic, still we  as an intermediary party won't be able to guarantee authentication. We will not  be held responsible for the loss caused by your&nbsp;  trusting consultant certification or website data.<br />
  As part of what is written  above, in case of having any loss, our liability will stay restricted to amount  paid&nbsp; for any product or services  purchased on our website. Any claim made against the product or services with  the use of website must be brought&nbsp;  within one year since the occurence of the action.&nbsp; Further if you use this site you agree to  waive&nbsp; any right to take part in a class  action suit for any losses or damages as a result of&nbsp; your use of the Website.</p>
<h4>WE DO NOT PROVIDE MEDICAL ADVICE</h4>
<p>The Content  that you obtain or receive from us, and our employees, contractors, partners,  sponsors, advertisers, licensors or otherwise through the Services is for  informational, scheduling and payment purposes only. All medically related  information,&nbsp; comes from independent healthcare  professionals and organizations and is for information purposes only.<br />
  No Space for Doctor-Patient Relationship Custom  Med Patient Services Inc.&nbsp;&nbsp; absolutely do  not&nbsp; create doctor-patient relationship.  Everything which has been placed on Custom Med Patient Services Inc. is for  your convenience, either&nbsp; its services or  just content. The reason behind placing it there is just for your information  purpose only.The information and content is not a substitute of proper health  examination or treatment. Gathering information regarding your query and  approaching a physician for a proper cure are two different things, so the  customers are advised not to take information as an alternate for proper  diagnosis after physical testing. </p>
<h4>Custom  Med Patient Services Inc.&nbsp; Consultation</h4>
  <p>&nbsp;Doctor- patient relationship would be  supported in Custom Med Patient Services Inc. , if an existing doctor-patient  relationship exists and Custom Med Patient Services Inc. video would create a  temporary relationship between doctor and patient. </p>
<h4>We  Aren't Your Doctor (Custom Med Patient Services Inc.)</h4>
<p>The reason behind mentioning  &quot;Your Doctor&quot;, means that we are emphasizing more on the formal  relationship between doctor-patient in the real world . The information that  you gather from experts is just for increasing your knowledge regarding your  query; they are not your actual doctor, physician or health examiner.  Participating on Custom Med Patient Services Inc. means you are consulting and  gathering the information in the first place which does not mean&nbsp; considering Custom Med Patient Services Inc.  as a substitute of your primary care physician. You can use Custom Med Patient  Services Inc. in times of need, for consulting with your existing doctor. </p>
<h4>No  Treatment &amp; Recommendation Available (Custom Med Patient Services Inc.)</h4>
<p>The users must know, the conversation on Custom Med Patient Services  Inc. does not mean that the consultant will either recommend you take any  medicine or there would be any guidance regarding the treatment. The consultant  has no right to diagnose any disease or give prescription for the cure. Using  the interaction as an alternate to real&nbsp;&nbsp;  physician examination is absolutely not recommended. In case if you need  proper treatment and appointment then you must visit your doctor in person for  having a proper health check-up.</p>
<p>Legal Compliance</p>
<p>You agree to comply with all applicable domestic and international laws,  statutes, ordinances, and regulations regarding your use of our Website. Custom  Med Patient Services Inc. reserves the right to investigate complaints or  reported violations of our Legal Terms and to take any action we deem  appropriate, including but not limited to canceling your Member account,  reporting any suspected unlawful activity to law enforcement officials,  regulators, or other third parties and disclosing any information necessary or  appropriate to such persons or entities relating to your profile, email addresses,  usage history, posted materials, IP addresses and traffic information, as  allowed under our Privacy Policy.</p>
<h4>Intellectual  Property</h4>
<p>Our Website may contain our  service marks or trademarks as well as those of our affiliates or other  companies, in the form of words, graphics, and logos. Your use of our Website  does not constitute any right or license for you to use such service  marks/trademarks, without the prior written permission of the corresponding  service mark/trademark owner. Our Website is also protected under international  copyright laws. The copying, redistribution, use or publication by you of any  portion of our Website is strictly prohibited. Your use of our Website does not  grant you ownership rights of any kind in our Website.</p>
<h4>Terms and Conditions for the  Consultants<u> </u></h4>
<p><strong>Independent Contractor</strong>: <br />
  The consultant working in our company is not an employee, agent or  joint venturer of the company; consultant is only an independent contractor and  will be responsible for the financial matters related to paying all the due  taxes occurred from his consultancy.&nbsp; </p>
<p><strong>Payment Method</strong> <br />
  The fees which consultant will charge from the customer will be  Consultant Rate and company on the other hand will charge its Administration  Management fee to the Consultant. The administration fees covers the services  to consultant, these services includes the platform provided to the consultant  , technical support and arranging sessions with the customers . Consultant is responsible for standard  phone, data and messaging charges from Consultant&rsquo;s wireless carrier. The  standard phone, messaging and data charges by the wireless carrier used by the  consultant are consultant's responsibility. The deduction of the Administration  Management Fee will be taken from the Consultant Rate and rest of the balance  will be transferred to consultant as Consultant Payout within 30 days.</p>
<p><strong>Consultant Profile</strong> <br />
  &nbsp;There are a few documents  that a consultant will provide to the company when asked. These documents  includes, background document, contact information, specific information  required for the website. Consultant  agrees that all information provided to Company is true,&nbsp; current, and complies with relevant law.&nbsp;&nbsp; All the documents given by  consultant will assure the company that the information provided is completely  true and current. In case of change in the contact, qualification, licensing or  any other relevant matter,&nbsp; the consultant  will immediately bring that matter into company&rsquo;s knowledge. Company keeps the  right to modify the text, and look of the profile and make the correction if  any misleading information is found in the profile.&nbsp;&nbsp; In case of&nbsp;  consultant breaching any rule set by the company, then either company or  the concerned department will have the right to ask for the compensation or  remedy&nbsp; against of the damages/loss done  to the company.</p>
<p><strong>Privacy Concerns</strong> <br />
  Keeping the privacy intact should have to be consultant's first  priority. No consultant will have the right to give the information gathered in  the consultation session to a third party. Using the information for marketing  consultant's own product or services is not allowed and neither sharing the  information with the third party nor using the information for personal  interest. Both the acts are strictly prohibited. All the information regarding,  company's practices, customer information, way of conducting business and other  confidential information will be kept confidential by the consultant as per  agreement except as provided by law. </p>
<p><strong>Defamation</strong><br />
  &nbsp;Consultant will not create a negative  image of the company on any forum. The other point is, which the consultant  must know that company will keep the feedback from its customers regarding the  services provided by the consultant .<br />
  <strong>Limitation on Consultancy</strong><br />
  &nbsp;There are certain laws and regulations  made for conducting standard information sessions. The restrictions on the  consultant's activity includes, medical advice, other information and advice  which are supposed&nbsp; to be rendered only  by a professional or someone who has built professional relationship.  Consultant's work is to provide the related information and not getting  involved in diagnosing the treatment and prescribing medicines in the  information session. The consultant must bring this into customer's knowledge  that the information session is not a replacement for the advice of a physician  after physical health examination. The information session should be taken as  an informational session and nothing more than this. The consultant will  neither endorse any medical advice associated with the information session nor  will be allowed to give medical or psychological advice along with the  guarantee of the result. </p>
<p><strong><em>&nbsp;</em></strong><strong>No Responsibility of the  Company</strong><strong> </strong><br />
During an information session, if any negligence made from  consultant's end then consultant will not have the right to claim against the  company or its&nbsp; officials . The  consultant will be solely liable for the outcome of the interaction between  consultant and customer no matter what the reason is. </p>
<p><strong>Way of Conducting Session</strong><br />
The consultant must follow the standard way for conducting the session. During  the information session, the environment in the surrounding must be peaceful,  session must be conducted in a quiet place . Consultant&nbsp; must act respectfully and talk in a  professional way.&nbsp; The consultant must be  available during the entire information session. </p>
<p>&nbsp;You agree that prescriptions in  Consultation not using video may be limited and may not include:<br />
  <br />
  1.Medications  for narcotics or DEA (Drug Enforcement Administration) <br />
  2.Medications for  Psychiatric illnesses<br />
  3.Medications  restricted by states whether by video or otherwise<br />
  4. Medications for  lifestyle&nbsp; such as erectile dysfunction  in males or sexual dysfunction in females or diet drugs<br />
  &nbsp;<br />
Some examples of  the drugs in each schedule are listed below.( Data given below taken from http://www.deadiversion.usdoj.gov/schedules/)  controlled substances (Schedule I, II, III, IV))</p>
<h3>Schedule  I Controlled Substances</h3>
<p>Substances  in this schedule have no currently accepted medical use in the United States, a  lack of accepted safety for use under medical supervision, and a high potential  for abuse.<br />
  Some  examples of substances listed in Schedule I are: heroin, lysergic acid  diethylamide (LSD), marijuana (cannabis), peyote, methaqualone, and  3,4-methylenedioxymethamphetamine (&quot;Ecstasy&quot;).</p>
<h3>Schedule  II/IIN Controlled Substances (2/2N)</h3>
<p>Substances  in this schedule have a high potential for abuse which may lead to severe  psychological or physical dependence.<br />
  Examples  of Schedule II narcotics include: hydromorphone (Dilaudid&reg;), methadone  (Dolophine&reg;), meperidine (Demerol&reg;), oxycodone (OxyContin&reg;, Percocet&reg;), and  fentanyl (Sublimaze&reg;, Duragesic&reg;).&nbsp; Other Schedule II narcotics include:  morphine, opium, codeine, and hydrocodone.<br />
  Examples  of Schedule IIN stimulants include: amphetamine (Dexedrine&reg;, Adderall&reg;),  methamphetamine (Desoxyn&reg;), and methylphenidate (Ritalin&reg;).<br />
  Other  Schedule II substances include: amobarbital, glutethimide, and pentobarbital.</p>
<h3>Schedule  III/IIIN Controlled Substances (3/3N)</h3>
<p>Substances  in this schedule have a potential for abuse less than substances in Schedules I  or II and abuse may lead to moderate or low physical dependence or high  psychological dependence.<br />
  Examples  of Schedule III narcotics include: products containing not more than 90  milligrams of codeine per dosage unit (Tylenol with Codeine&reg;), and buprenorphine  (Suboxone&reg;).</p>
<h3>Examples  of Schedule IIIN non-narcotics include: benzphetamine (Didrex&reg;),  phendimetrazine, ketamine, and anabolic steroids such as Depo&reg;-Testosterone.<br />
  Schedule IV Controlled Substances </h3>
<p>Substances  in this schedule have a low potential for abuse relative to substances in  Schedule III.<br />
  Examples  of Schedule IV substances include: alprazolam (Xanax&reg;), carisoprodol (Soma&reg;),  clonazepam (Klonopin&reg;), clorazepate (Tranxene&reg;), diazepam (Valium&reg;), lorazepam  (Ativan&reg;), midazolam (Versed&reg;), temazepam (Restoril&reg;), and triazolam  (Halcion&reg;).</p>
<p><strong>Revisions and Errata</strong><strong><br />
</strong>The materials appearing on Custom Med Patient  Services Inc.&rsquo;s Website could include technical, typographical, or photographic  errors. Custom Med Patient Services Inc. does not warrant that any of the  materials on its Website are accurate, complete, or current. Custom Med Patient  Services Inc. may make changes to the materials contained on its Website at any  time without notice. Custom Med Patient Services Inc. does not, however, make any  commitment to update the materials.</p>
<p>Under a federal law called the Health  Insurance Portability and Accountability Act (&ldquo;HIPAA&rdquo;), some of this health and health-related information may  be considered &ldquo;protected health information&rdquo; &nbsp;if such information is received from or on  behalf of &nbsp;Healthcare Providers.<br />
  Safeguards  for PHI<br />
  HIPAA protects the privacy and  security of your Protected Health Information by limiting the uses and  disclosures of this information &nbsp;by most  healthcare providers and&nbsp; companies, like  Custom Med Patient Services,Inc., called &ldquo;Business Associates&rdquo;. &nbsp;</p>
<p>As a condition of creating your &nbsp;account, you are required to read and agree to  our Privacy Policy. </p>
<p>By&nbsp;  using this site , you give us &nbsp;written  permission to allow us to use and disclose your Protected Health Information ,  if we act as&nbsp; &nbsp;a Business Associate of Your Healthcare  consultants .&nbsp; When we are &nbsp;&nbsp;not  working on behalf of Your Healthcare Providers, but &nbsp;instead working on our own behalf.&nbsp; Custom Med Patient Services Inc. is not  working as a Business Associate and the HIPAA requirements that apply to  Business Associates will not apply to such uses and disclosures.<br />
    <br />
    <strong>Arbitration</strong><br />
  Arbitration is an agreement for  resolving disputes between one or more person with no jury trial&nbsp; being involved in it.<br />
  Arbitration is made to  resolve disputes of the parties. It involves no jury trial. The rules are  implemented&nbsp; in accordance with established arbitration rules of  the AAA. The basic objective should  have to be resolving a dispute with minimum expense incurred in it and take the  maximum satisfaction out from it. Approaching us first for resolving an issue  would be a wise step.&nbsp;&nbsp;&nbsp; The step for  resolving a dispute must be started with an AAA arbitrator in Santa Clara  County, California. The resolving step must be initiated within one year of the  date it happened or within maximum time allowed by law. Arbitration allows an  individual to resolve an issue . The jury has no right to intervene in between,  the proceedings will be governed through the AAA procedure. It is important  that the dispute must be kept&nbsp;  confidential by both the parties. Furthermore, if any part of this  arbitration agreement seems invalid then it shall be detached from the rest of  the clauses and the  rest of this clause and agreement shall be valid. <br />
  When you make a payment through our Services to a Healthcare  Provider for online consultation, your payment card information is processed by  our&nbsp; partner, Stripe (https://Stripe.com).  Stripe collects your voluntarily provided payment card information necessary to  process your payment. Stripe&rsquo;s use and storage of information it collects is  governed by Stripe&rsquo;s applicable terms of service and privacy policy.&nbsp;&nbsp; </p>
<p><strong>Disclaimer<br />
  </strong>The materials on&nbsp;<strong>Custom Med Patient  Services Inc.</strong>'s Website are provided &quot;as is&quot;&nbsp;<strong>Custom Med  Patient Services Inc.</strong>&nbsp;makes no warranties, expressed or implied, and  hereby disclaims and negates all other warranties, including without  limitation, implied warranties or conditions of merchantability, fitness for a  particular purpose, or non-infringement of intellectual property or other  violation of rights. Further,&nbsp;<strong>Custom Med Patient Services Inc.</strong>&nbsp;does  not warrant or make any representations concerning the accuracy, likely  results, or reliability of the use of the materials on its Internet Website or  otherwise relating to such materials or on any sites linked to this site. The  Website serves as a venue for Individuals to purchase distinct service or  products. Neither Custom Med Patient Services Inc. nor the Website has control  over the quality or fitness for a particular function of a product. Custom Med  Patient Services Inc. likewise has no control over the accuracy, reliability,  completeness, or timeliness of the User-submitted details and makes no  representations or warranties about any info on the Site.</p>
<p>  THE WEBSITE AND ALL DETAILS, CONTENT, MATERIALS, PRODUCTS  (INCLUDING SOFTWARE APPLICATION) AND SERVICES CONSISTED OF ON OR OTHERWISE MADE  AVAILABLE TO YOU THROUGH THIS WEBSITE ARE PROVIDED BY Custom Med Patient  Services Inc. ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS,  UNLESS OTHERWISE SPECIFIED IN WRITING. Custom Med Patient Services Inc. MAKES  NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, ABOUT THE  OPERATION OF THIS Website OR THE INFO, MATERIAL, MATERIALS, PRODUCTS (INCLUDING  SOFTWARE) OR SERVICES CONSISTED OF ON OR OTHERWISE MADE AVAILABLE TO YOU  THROUGH THIS SITE, UNLESS OTHERWISE POINTED OUT IN WRITING. YOU EXPRESSLY AGREE  THAT YOUR USE OF THIS WEBSITE IS AT YOUR OWN RISK.<br />
  TO THE COMPLETE EXTENT PERMISSIBLE BY APPLICABLE LAW, Custom Med  Patient Services Inc. DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING,  BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND PHYSICAL FITNESS  FOR A PARTICULAR PURPOSE. Custom Med Patient Services Inc. DOES NOT WARRANT  THAT THIS WEBSITE; DETAILS, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE  APPLICATION) OR SERVICES CONSISTED OF ON OR OTHERWISE MADE AVAILABLE TO YOU  THROUGH THE SITE; ITS SERVERS; OR EMAIL SENT FROM Custom Med Patient Services  Inc. ARE WITHOUT VIRUSES OR OTHER HARMFUL ELEMENTS. Custom Med Patient Services  Inc. WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THE  Website OR FROM ANY DETAILS, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE  APPLICATION) OR SERVICES CONSISTED OF ON OR OTHERWISE MADE AVAILABLE TO YOU  WITH THIS SITE, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL,  PUNITIVE, AND CONSEQUENTIAL DAMAGES, UNLESS OTHERWISE POINTED OUT IN WRITING.  UNDER NO SCENARIO SHALL Custom Med Patient Services Inc.'S LIABILITY DEVELOPING  FROM OR IN CONNECTION WITH THE WEBSITE OR YOUR USE OF THE WEBSITE, DESPITE THE  REASON FOR ACTION (WHETHER IN AGREEMENT, TORT, BREACH OF SERVICE WARRANTY OR  OTHERWISE), GO BEYOND $100.</p>
<p><strong>Links to Other Websites</strong><br />
  Our Website may contain links to third party websites. These links are provided  solely as a convenience to you. By linking to these websites, we do not create  or have an affiliation with, or sponsor such third party websites. The  inclusion of links within our Website does not constitute any endorsement,  guarantee, warranty, or recommendation of such third party websites. Custom Med  Patient Services Inc. has no control over the legal documents and privacy  practices of third party websites; as such, you access any such third party  websites at your own risk.</p>
<p><strong>Site Terms of Use Modifications</strong><br />
  Custom Med Patient Services Inc. may revise these terms of use for its Website  at any time without notice. By using this Website you are agreeing to be bound  by the then current version of these Terms and Conditions of Use.</p>
<p><strong>Governing Law</strong><br />
  Any claim relating to Custom Med Patient Services Inc.&rsquo;s Website shall be  governed by the laws of California without regard to its conflict of law  provisions, and You consent to exclusive jurisdiction and venue in such courts.</p>
<p><strong>Indemnity<br />
  </strong>You accept defend, indemnify, and hold safe  Custom Med Patient Services Inc., its affiliates, and their corresponding  officers, directors, agents and workers, from and against any claims, actions  or demands, including without limitation affordable legal, accounting, and  other provider charges, affirming or resulting from (i) any Content of most  material You offer to the Site, (ii) Your use of any Content, or (iii) Your  breach of the terms of these Terms. Custom Med Patient Services Inc. will  provide notice to You promptly of any such claim, match, or case.</p>
<p><strong>General Terms</strong><br />
  Our Legal Terms shall be treated as though it were executed and performed in  California, United States and shall be governed by and construed in accordance  with the laws of California, United States without regard to conflict of law  principles. In addition, you agree to submit to the personal jurisdiction and  venue of such courts. Any cause of action by you with respect to our Website,  must be instituted within one (1) year after the cause of action arose or be  forever waived and barred. Should any part of our Legal Terms be held invalid  or unenforceable, that portion shall be construed consistent with applicable  law and the remaining portions shall remain in full force and effect. To the  extent that any Content in our Website conflicts or is inconsistent with our  Legal Terms, our Legal Terms shall take precedence. Our failure to enforce any  provision of our Legal Terms shall not be deemed a waiver of such provision nor  of the right to enforce such provision. The rights of Custom Med Patient  Services Inc. under our Legal Terms shall survive the termination of our Legal  Terms.</p>
<p>  You agree that you are not located in a country subject to  a U.S. Government embargo, or called a &ldquo;terrorist supporting&rdquo; country, and that  you are not listed on any U.S. Government list of prohibited or restricted entities. </p>

</div><!--text-center col-md-10-->
<div class="col-md-1"></div><div class="clearfix"></div>

  </div><!--row margin-bottom-40-->
</div><!--col-md-12-->





</div>
</div>
 </div>